### ISSUE TITLE
klib artifact for common library is missing in maven repo

### ISSUE THREAD

**Issue by b3er** [respawn-app/KMPUtils#11]
Klib artifact is missing for iosarm64 target
url at https://repo.maven.apache.org/maven2/pro/respawn/kmmutils/common-iosarm64/1.2.0/common-iosarm64-1.2.0.klib returns 404 error

**Comment by Nek-12** [comment]
Thanks for mentioning, this happens sometimes due to issues with publishing of KMP projects and is hard to track. I will release a general dependency update and it should fix this. Haven't experienced this bug with other repos after kotlin 1.9.20
